name: Caller

on:
  push:
    branches:
      - 'main'
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:

  master:
    uses: aneeshchackov/master/.github/workflows/master.yml@main

  build:
    name: Validation_Build
    runs-on: windows-latest
    steps:
      - name: Run After Successful Workflow
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: echo "This job runs after the previous workflow succeeded"
      - name: Checkout repository
        uses: actions/checkout@v4
        # with:
          # repository: aneeshchackov/master
      - name: Download Source Artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: artifact
