name: Caller

on:
  push:
    branches:
      - 'main'
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:

  master:
    uses: aneeshchackov/master/.github/workflows/master.yml@main

  build:
    # name: Validation_Build
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest    
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run After Successful Workflow
        # if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          echo "This job runs after the previous workflow succeeded"
          echo ${{github.event.workflow_run.conclusion}}
      - name: Checkout repository
        uses: actions/checkout@v4.1.0
        # with:
          # repository: aneeshchackov/master
      - name: Download Source Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: artifact
          path: artifact
