name: Caller

on:
  push:
    branches:
      - 'main'
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:

  master:
    uses: aneeshchackov/master/.github/workflows/master.yml@main

  build:
    name: Validation_Build
    runs-on: widows-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Source Artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: artifact
